version: '2'

services:
  game-ui:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    environment:
      - APP_CONFIG='{"brokerUrl":"http://localhost:9001", "instanceName":"1"}'
